### ISSUE TITLE
UI Mocks

### ISSUE THREAD

**Issue by richardd3ng** [richardd3ng/Shelf-Stability-System#6]

**Comment by Brokemia** [comment]
![image](https://github.com/richardd3ng/Shelf-Stability-System/assets/37253216/ca8f84a8-1a9a-423a-be88-b2eb6a17257f)
![image](https://github.com/richardd3ng/Shelf-Stability-System/assets/37253216/ac904961-a8d3-4954-b149-e94c38f760c5)![image](https://github.com/richardd3ng/Shelf-Stability-System/assets/37253216/68916ccd-14eb-416f-ba01-9d01e371b1ec)
